### PR TITLE
Added dark mode

### PR DESCRIPTION
**Pull request by pvcodes**

### CODE REVIEW

**Comment by pvcodes** [comment]
Hey @achris-alonzo30,

I loved this GitHub-style portfolio theme! At first glance, the only thing missing was a dark mode, so I went ahead and added it. Take a look if you're interested—I've created a PR. Feel free to merge it or close it, totally up to you.

By the way, great work!

PEACE!

**Comment by pvcodes** [comment]
you have a link demo here: https://pvcodes.me

**Comment by dolev146** [comment]
> https://pvcodes.me

thank you :) that looks good

**Comment by dolev146** [comment]
Even then it's merged you need to build for it to run and deploy I think ?

**Comment by achris-alonzo30** [comment]
thats done, check if it works: [Link](https://github-portfolio-pied.vercel.app/)

Just pull the latest change

**Comment by dolev146** [comment]
@pvcodes   @achris-alonzo30 

hey guys, can you teach me how did you made the theme toggle?


because I don't see it passed a a props to components for example buttons and texts


so I am trying to solve this bug for the title of the work experience its black only, and not changing to the selected theme

image


image


do you have idea how to solve it?

**Comment by achris-alonzo30** [comment]
Go to the file src/components/Experience.tsx 

then look for this code: `<h2 className="text-xl font-bold mb-4">Work Experience</h2>`

then add `text-background` to the className. Here's what's going to look like: 

`<h2 className="text-xl font-bold mb-4 text-background">Work Experience</h2>`

**Comment by dolev146** [comment]
this didnt worked because the background and the text would end up the same color

I understood now its a class name from tailwind so I asked gpt to fix that based on tailwind

```
<h2 className="text-xl font-bold mb-4 text-black dark:text-white">Work Experience</h2>
```

do you want a PR for that? 

i lack a bit familiarity with nextjs and tailwind sorry for interruptions and thank you a lot for the help!!!

**Comment by achris-alonzo30** [comment]
@dolev146 right on! chatgpt always know hte answers hehe

for sure go make a PR! feel free to contribute and don't forget to share your work once you're done! love to see it

**Comment by dolev146** [comment]
https://github-portfolio-red.vercel.app/

**Comment by ZeeshanMukhtar1** [comment]
> What about this : https://www.codewithzeeshan.me/

**Comment by achris-alonzo30** [comment]
> > What about this : https://www.codewithzeeshan.me/

yours is awesome brother!

**Pull request merged**
